### ISSUE TITLE
add navigation bar

### ISSUE THREAD

**Issue by svenvonwerner** [svenvonwerner/capstone-project#11]
## Value proposition
**As a** user
**I need** to see a navigationbar on every side
**to be able to** to be able to switch to the subsides flexibility"

## Description
![Bildschirmfoto 2022-03-18 um 14 27 54](https://user-images.githubusercontent.com/97452283/159011411-ce8df4bf-ecc9-4fae-a32f-8e2b91ef2744.png)

## Acceptance Criteria

- [ ] A navigation bar is shown
- [ ] A button to switch to the subside "create challenges" is shown
- [ ] A button to switch to the subside "list challenges" is shown  

## Tasks

- [ ] **components/navigation bar**
- [ ]   Storybook
- [ ]   Testing
- [ ]   Implementation navigation bar 
- [ ]   Implementation button "create challenges"
- [ ]   Connecting button to subside "create challenges" 
- [ ]   Implementation button "list challenges"  
- [ ]   Connecting button to subside "list challenges"
- [ ]   Add navigation bar to the App
