### ISSUE TITLE
Delete-Button

### ISSUE THREAD

**Issue by svenvonwerner** [svenvonwerner/capstone-project#13]
## Value proposition

**As a** user
**I need** a function 
**to be able** to delete my challenge card 

## Acceptance Criteria

- [x] A button to delete a item is shown on the single card
- [x] Button has the functionality to delete a card

## Tasks

- [x] Components/Card
    - [x] Add an icon to the card
