### ISSUE TITLE
Add Edit Button

### ISSUE THREAD

**Issue by svenvonwerner** [svenvonwerner/capstone-project#14]
## Value proposition

**As a** user
**I need** a function 
**to be able** to update my challenge card 

## Acceptance Criteria

- [ ] A button to edit a item is shown on every single card
- [ ] Button has the functionality to edit a card

## Tasks

- [ ] Components/Card
    - [ ] Add an an button "Edit" to the card
    - [ ]  Add an functionality to delete the card
    - [ ] Testing
