### ISSUE TITLE
Check off Photo-Challenge

### ISSUE THREAD

**Issue by svenvonwerner** [svenvonwerner/capstone-project#2]

**Comment by svenvonwerner** [comment]
## Value proposition
**As a** user
**I need** a Bookmark Button to check-off the photo-challenge-Card
**to be able to** see, which challenge is finished

## Description

## Acceptance Criteria
- [ ] Bookmark button should be visible on the card
- [ ] Bookmark button should be toggleable
- [ ] Color of the bookmark button should change

## Tasks

- [ ] Components/PhotoChallengCards
   - [ ] Storybook
   - [ ] Add button 
   - [ ] Place icon
   - [ ] Styling
   - [ ] Testing
   - [ ] Add to app
