### ISSUE TITLE
List of Photo-Challenges

### ISSUE THREAD

**Issue by svenvonwerner** [svenvonwerner/capstone-project#2]
## Value proposition

**As a** user
**I need** to see a list of Photo-Challenges
**to be able** to remember them

## Description
![Bildschirmfoto 2022-03-04 um 16 50 07](https://user-images.githubusercontent.com/97452283/156795493-3a54de3e-7c46-450b-8eef-83177284724c.png)

## Acceptance Criteria

- [ ] Title is shown on page
- [ ] Title is fixed on page
- [ ] List of Photo-Challenges-Cards is scrollable

- [ ] On every Card a Subtitle
- [ ] Every Card has Description

## Tasks

- [ ] Global Styles

- [ ] components/PhotoChallengeCards
   - [ ] Storybook
   - [ ] Styling
   - [ ] Testing

## components/PhotoChallengeCardsList

- [ ]  Add PhotoChallengeCard
   - [ ] Storybook
   - [ ] Tests
   - [ ] Styling
