### ISSUE TITLE
Connecting cloud-based image storage

### ISSUE THREAD

**Issue by svenvonwerner** [svenvonwerner/capstone-project#22]
## Value proposition

**As a** user
**I need** to upload my photos 
**to be able to** see a collection special to my challenge

## Description

![Bildschirmfoto 2022-03-25 um 12 07 50](https://user-images.githubusercontent.com/97452283/160110018-09ee8fe7-bf9c-46a6-b436-4f15dcbb4628.png)
-b4d0-72ac9012b724.png)

## Acceptance Criteria

- [ ] A button for uploading is shown
- [ ] After upload my photo I see it in my collection on the card

## Tasks

- [ ] Connecting api/cloud-based image storage
- [ ] Storyboard
- [ ] Implementation a upload button on card
- [ ] Create a upload-functionality for the upload button
- [ ] Testing
