### ISSUE TITLE
Check off Photo-Challenge

### ISSUE THREAD

**Issue by svenvonwerner** [svenvonwerner/capstone-project#3]
## Value proposition

**As a** user
**I need** a bookmark button to check-off the photo-challenge-Card
**to be able** to see, which challenge is finished

## Description
![Bildschirmfoto 2022-03-04 um 16 50 15](https://user-images.githubusercontent.com/97452283/156802142-be32be87-043c-4f40-b8de-1989183d9b6f.png)

## Acceptance Criteria

- [ ] Bookmark button should be visible on the card
- [ ] Bookmark button should be toggleable
- [ ] Color of the bookmark button should change

## Tasks

- [ ] Components/PhotoChallengCards
   - [ ]     Storybook
   - [ ]     Add button 
   - [ ]     Place icon
   - [ ]     Styling
   - [ ]     Testing
   - [ ]     Add to app
