### ISSUE TITLE
Add Form

### ISSUE THREAD

**Issue by svenvonwerner** [svenvonwerner/capstone-project#8]
## Value proposition

**As a** user
**I need** a form  
**to be able** save information for a single photo challenge

## Description
![user_story_capstone](https://user-images.githubusercontent.com/97452283/158371389-e63552cd-79d5-40c0-8846-38dedb692b91.png)

## Acceptance Criteria

- [x] An input field for title is shown
- [x] An input field for categories is shown
- [x] An input field for name is shown  
- [x] An input field for description is shown
- [x] A button for saving is shown

## Tasks

- [x] Components/Form-CreateChallenge
    - [x]  Add form
    - [x] Add button "Save"
    - [x]  Storybook
    - [x]  Add input field for title
    - [x]  Add input field for categories
    - [x]  Add input field for description
    - [x]  Add input field for name (author)
    - [x]  Testing
    - [x]  Styling
